service: tom-cohort-5
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  delfrinandoapi:
    handler: index.pranata
    events:
      - httpApi:
          path: /
          method: get

  pranatapost:
    handler: index.pranatapost
    events:
      - httpApi:
          path: /pranata
          method: post

plugins:
  - serverless-offline